server:
  port: 8080

spring:
  application:
    name: api-gateway
  web-application-type: reactive
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        default-filters: TokenRelay
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/product/**
          - id: tenant-service
            uri: lb://tenant-service
            predicates:
              - Path=/tenant/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${shop.registry.url}
    instance:
      hostname: ${shop.registry.hostname}

  shop:
    iam:
      url: ${iamBaseUrl:http://localhost:8080}
    registry:
      url: ${registryBaseUrl:http://localhost:8083}
      hostname: ${registryHostname:localhost}


