server:
  port: 0
  servlet:
    context-path: /shop
  forward-headers-strategy: framework

spring:
  application:
    name: PRODUCT-SERVICE
  data:
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: pageNumber
        default-page-size: 10
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: {shop.iam.url}/realms/My-Realm/protocol/openid-connect/certs
  rabbitmq:
    addresses: ${RABBIT_MQ_HOST:localhost}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    port: ${RABBIT_MQ_PORT:5672}
    virtualHost: ${RABBIT_MQ_VIRTUALHOST:prod}
  jpa:
    open-in-view: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: {shop.registry.url}
    instance:
      hostname: {shop.registry.hostname}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

  shop:
    iam:
      url: ${iamBaseUrl:http://localhost:8080}
    registry:
      url: ${registryBaseUrl:http://localhost:8083}
      hostname: ${registryHostname:localhost}
