server:
  port: 0

spring:
  application:
    name: product
  data:
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: pageNumber
        default-page-size: 1
   
   datasource:
    url: ${MYSQL_DB_URI:jdbc:mysql://127.0.0.1:3313?useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        tenant_identifier_resolver: co.ke.personal.student.config.datasource.TenantIdentifierResolver
        multi_tenant_connection_provider: co.ke.personal.student.config.datasource.SchemaMultiTenantConnectionProvider
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    url: ${hibernate.connection.url}
    user: ${hibernate.connection.username}
    password: ${hibernate.connection.password}
    baselineOnMigrate: true
    enabled: false
 
  batch:
    jdbc:
      initialize-schema: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: {shop.registry.url}
    instance:
      hostname: {shop.registry.hostname}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

  shop:
    iam:
      url: ${iamBaseUrl:http://localhost:8080}
    registry:
      url: ${registryBaseUrl:http://localhost:8083}
      hostname: ${registryHostname:localhost}
