server:
  port: 8083

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  shop:
    iam:
      url: ${iamBaseUrl:http://localhost:8080}
    registry:
      url: ${registryBaseUrl:http://localhost:8083}
      hostname: ${registryHostname:localhost}
