server:
  port: 0

spring:
  application:
    name: tenant
  datasource:
    url: ${MYSQL_DB_URI:jdbc:mysql://127.0.0.1:3307/tenant}
    name: tenant
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${shop.registry.url}

shop:
  iam:
    url: ${iamBaseUrl:http://localhost:8081}
    username: ${masterUsername:admin}
    password: ${masterPassword:password}
    clientId: ${keycloakClientId:tenant-service}
    secret: ${keycloakClientSecret:ixLpGjwRUgwIkvVTwXlwnfjWVx0EeubD}
      
  registry:
    url: ${EUREKA_URI:http://localhost:8083/eureka}
