server:
  port: 0

spring:
  application:
    name: tenant
  datasource:
    url: ${MYSQL_DB_URI:jdbc:mysql://127.0.0.1:3307/tenant}
    name: tenant
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${shop.registry.url}

keycloak:
  realm: master
  resource: tenant-service
  auth-server-url: ${shop.iam.url}
  credentials:
    secret: ixLpGjwRUgwIkvVTwXlwnfjWVx0EeubD

shop:
  iam:
    url: ${iamBaseUrl:http://localhost:8080}
    template:
      issuer: ${shop.iam.url}/auth/realms/%s,
      authorization_url: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/auth,
      token_uri: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/token,
      introspection_uri: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/token/introspect,
      userinfo_uri: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/userinfo,
      end_session_uri: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/logout,
      jwks_uri: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/certs,
      check_session_iframe: ${shop.iam.url}/auth/realms/%s/protocol/openid-connect/login-status-iframe.html,
      
  registry:
    url: ${EUREKA_URI:http://localhost:8083/eureka}
